"""
Interview taxonomy: category -> specific areas.

Kept here as a simple Python dict for now. Once the project grows, this is a
good candidate to move into Data_Layer/taxonomy/categories.yaml so the backend
and the question banks read the same source of truth.
"""

CATEGORIES = {
    "DSA / Coding": [
    "Arrays",
    "Strings",
    "Hashing",
    "Linked Lists",
    "Stacks & Queues",
    "Trees",
    "Binary Search Trees",
    "Heaps & Priority Queues",
    "Graphs",
    "Recursion & Backtracking",
    "Dynamic Programming",
    "Greedy Algorithms",
    "Binary Search",
    "Sorting",
    "Two Pointers",
    "Sliding Window",
    "Intervals",
    "Bit Manipulation",
    "Trie",
    "Union Find (Disjoint Set)",
    "Segment Tree & Fenwick Tree",
    "Monotonic Stack / Queue",
    "Mathematics & Number Theory",
    "String Algorithms",
    "Advanced Graph Algorithms",
    "Concurrency & Multithreading",
    "Fast & Slow Pointers",
    "Merge Intervals",
    "Cyclic Sort",
    "Top K Elements",
    "Tree DFS",
    "Tree BFS",
    "Prefix Sum",
    "Difference Array"
    ],

    "System Design": [
    "System Design Fundamentals",
    "Scalability",
    "Caching",
    "Load Balancing",
    "Databases",
    "Distributed Systems",
    "Messaging & Event-Driven Architecture",
    "Consistency & Reliability",
    "Microservices",
    "API Design",
    "Observability & Monitoring",
    "Security",
    "Storage Systems",
    "Real-Time Systems",
    "System Design Case Studies"
],

  "ML / AI Engineering": [
    "Machine Learning Fundamentals",
    "Supervised Learning",
    "Unsupervised Learning",
    "Feature Engineering",
    "Model Evaluation & Metrics",
    "Statistics & Probability",
    "Linear Algebra for ML",
    "Optimization",
    "Deep Learning",
    "Computer Vision",
    "Natural Language Processing",
    "Transformers & LLMs",
    "Prompt Engineering",
    "RAG Systems",
    "Agentic AI",
    "Reinforcement Learning",
    "MLOps & Model Deployment",
    "Distributed Training",
    "Responsible AI",
    "ML System Design"
],
    "Data Engineering": [
    "SQL",
    "Data Modeling",
    "Data Warehousing",
    "ETL / ELT",
    "Batch Processing",
    "Stream Processing",
    "Apache Spark",
    "Apache Kafka",
    "Data Lakes & Lakehouses",
    "Distributed Systems",
    "Workflow Orchestration",
    "Data Quality",
    "Cloud Data Engineering",
    "Performance Optimization",
    "Data Engineering System Design"
],

"Behavioral": [
    "Leadership",
    "Ownership",
    "Problem Solving",
    "Conflict Resolution",
    "Teamwork & Collaboration",
    "Communication",
    "Stakeholder Management",
    "Project Management",
    "Decision Making",
    "Handling Ambiguity",
    "Learning & Growth",
    "Failure & Resilience",
    "Innovation & Initiative",
    "Customer Focus",
    "Mentoring & Coaching",
    "Time Management & Prioritization",
    "Influencing Without Authority",
    "Cross-Functional Collaboration",
    "Career & Motivation",
    "Behavioral Case Studies"
],
}

DIFFICULTY_LEVELS = ["Easy", "Medium", "Hard"]

QUESTION_SOURCES = [
    "Static bank",        # curated questions from Data_Layer/static_questions
    "From books",         # retrieved from ingested resources (RAG)
    "LLM-generated",      # freshly generated by the model
]
